<?php

namespace Omnipay\RocketGate\Message;

/**
 * Class PurchaseRequest
 *
 * This class is used for making Card & Token Payment.
 *
 * ### Example
 * <code>
 * // Initialize the gateway
 * $gateway = Omnipay::create('RocketGate');
 * $gateway->initialize(array(
 *     'merchantID'       => 'XXXXXXXXXXXX',
 *     'merchantPassword' => 'XXXXXXXXXXXX',
 *     'testMode'         => true,
 * ));
 *
 * // Create a credit card object
 * $card = new CreditCard(array(
 *     'firstName'       => 'Example',
 *     'lastName'        => 'Customer',
 *     'number'          => '4242424242424242',
 *     'expiryMonth'     => '01',
 *     'expiryYear'      => '2032',
 *     'cvv'             => '123',
 *     'email'           => 'customer@example.com',
 *     'billingAddress1' => 'Consolacion, Cebu',
 *     'billingCountry'  => 'SG',
 *     'billingCity'     => 'Philippines',
 *     'billingPostcode' => '567278',
 *     'billingState'    => 'Philippines',
 * ));
 *
 * // Do a purchase transaction on the gateway
 * $transaction = $gateway->purchase(array(
 *     'amount'      => '50.00',
 *     'currency'    => 'USD',
 *     'card'        => $card,
 *     'transactorId'  => random_int(0, 1000000000),
 *     'transactionId' => random_int(0, 1000000000),
 * ));
 *
 * $response = $transaction->send();
 * if ($response->isSuccessful()) {
 *     echo "Purchase transaction was successful!\n";
 *     $token = $response->getCardReference();
 *     echo "Card reference = " . $token . "\n";
 * }
 * </code>
 *
 * #### Token Payment
 *
 * To obtain a card reference (the cardReference parameter) a previous purchase
 * call must be completed successfully.  After the successful completion, check
 * the result of getCardReference() on the response:
 *
 * <code>
 * // Do a Token transaction on the gateway
 * $transaction = $gateway->purchase(array(
 *     'amount'        => '50.0',
 *     'currency'      => 'USD',
 *     'transactorId'  => random_int(0, 1000000000),
 *     'transactionId' => random_int(0, 1000000000),
 *     'cardReference' => $response->getCardReference(),
 * ));
 *
 * $response = $transaction->send();
 * if ($response->isSuccessful()) {
 *     echo "Purchase transaction was successful!\n";
 *     $sale_id = $response->getTransactionReference();
 *     echo "Transaction reference = " . $sale_id . "\n";
 * }
 * </code>
 *
 * @date      08/02/2019
 * @author    markbonnievestil (mbvestil@gmail.com)
 */
class PurchaseRequest extends AbstractRequest
{
    /**
     * @return mixed
     */
    public function getTransactorId()
    {
        return $this->getParameter('transactorId');
    }

    /**
     * @param $value
     * @return \Omnipay\Common\Message\AbstractRequest
     */
    public function setTransactorId($value)
    {
        return $this->setParameter('transactorId', $value);
    }

    /**
     * @return string
     */
    public function getUse3DSecure()
    {
        return $this->getParameter('use3DSecure');
    }

    /**
     * @param $value
     * @return \Omnipay\Common\Message\AbstractRequest
     */
    public function setUse3DSecure($value)
    {
        return $this->setParameter('use3DSecure', $value);
    }

    /**
     * Prepare the data to be set to RocketGate's SDK
     *
     * Note : Each array key is the method name in RocketGates SDK
     *      i.e $data['MERCHANT_CUSTOMER_ID'] will set the customer id by calling
     *          SDK's GatewayRequest::MERCHANT_CUSTOMER_ID()
     *
     * @return array
     * @throws \Omnipay\Common\Exception\InvalidRequestException
     */
    public function getData()
    {
        $data = parent::getData();

        $this->validate('amount', 'currency');

        $data['AMOUNT']    = $this->getAmount();
        $data['CURRENCY']  = strtolower($this->getCurrency());
        $data['IPADDRESS'] = $this->getClientIp();

        // transaction identifier generated by the merchant website.
        if ($this->getTransactionId()) {
            $data['MERCHANT_INVOICE_ID'] = $this->getTransactionId();
        }

        // customer's identifier generated by the merchant website.
        if ($this->getTransactorId()) {
            $data['MERCHANT_CUSTOMER_ID'] = $this->getTransactorId();
        }

        // by default ignore, a new parameter must be passed if you need to support these
        $data['SCRUB'] = "IGNORE";

        if ($this->getCardReference()) {
            $data['CVV2_CHECK'] = "NO";
            $data['AVS_CHECK']  = "NO";
            $data['CARD_HASH']  = $this->getCardReference();
        } else {
            $this->validate('card');
            $card = $this->getCard();

            $data['CUSTOMER_FIRSTNAME'] = $card->getFirstName();
            $data['CUSTOMER_LASTNAME']  = $card->getLastName();
            $data['EMAIL']              = $card->getEmail();
            $data['BILLING_ADDRESS']    = $card->getBillingAddress1() . ' ' . $card->getBillingAddress2();
            $data['BILLING_CITY']       = $card->getBillingCity();
            $data['BILLING_ZIPCODE']    = $card->getBillingPostcode();
            $data['BILLING_STATE']      = $card->getBillingState();
            $data['BILLING_COUNTRY']    = $card->getBillingCountry();
            $data['CARDNO']             = $card->getNumber();
            $data['CVV2']               = $card->getCvv();
            $data['EXPIRE_MONTH']       = $card->getExpiryMonth();
            $data['EXPIRE_YEAR']        = $card->getExpiryYear();

            $data['CVV2_CHECK'] = "YES";
            $data['AVS_CHECK']  = "IGNORE";

            $data['USE_3D_SECURE'] = $this->getUse3DSecure();
        }

        return $data;
    }

    /**
     * {@inheritdoc}
     */
    public function serviceMethod()
    {
        return 'PerformPurchase';
    }
}